- name: Test for facts
  hosts: two 
  remote_user: root
  tasks:
    - name: show facts message
      debug:
        msg: >
         Host is {{ansible_fqdn}}.
         IP is {{ansible_default_ipv4.address}}
  
