---
- name: start demo vm
  hosts: localhost
  remote_user: root
  vars:
    demovmip: 192.168.122.125
    chkport: 22
  tasks:
  - name: start test kvm - rhel7.1
    virt: name=rhel7.1 state=running
  - name: wait for 10 seconds 
    wait_for: host={{ demovmip }} port={{ chkport }} delay=10 timeout=60  state=started
  - name: Notification
    mail:
      host: localhost
      port: 25
      to: Joe Yu <sleepyjoeyu@gmail.com>
      subject: demo VM is ready
      body: 'System {{ demovmip }} has been successfully started.'

